# Dev Configuration

# Salesforce Configuration
salesforce:
  username: "diljot@diljot.com"
  
# Listener Configuration
http:
  host:  "0.0.0.0"
  port: "8081"
  readTimeout: "30000"

# API Configuration
api:
  id: "18645792"